// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpzEeUstat8kgxVmaPRJgR5Gi356MTWv8',
    appId: '1:1078053511044:web:4e1d43f97c2a76a70ac7d1',
    messagingSenderId: '1078053511044',
    projectId: 'app-sg-db',
    authDomain: 'app-sg-db.firebaseapp.com',
    storageBucket: 'app-sg-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ4SaH-7HQejO5ZbrQWr3Q3jhmRANBvgI',
    appId: '1:1078053511044:android:defec9ccc800e43d0ac7d1',
    messagingSenderId: '1078053511044',
    projectId: 'app-sg-db',
    storageBucket: 'app-sg-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzBewhBk_rrKtWF20i-6HCK8T_2Xfrta8',
    appId: '1:1078053511044:ios:e6e42e6824eb06f40ac7d1',
    messagingSenderId: '1078053511044',
    projectId: 'app-sg-db',
    storageBucket: 'app-sg-db.firebasestorage.app',
    iosBundleId: 'com.example.appSg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzBewhBk_rrKtWF20i-6HCK8T_2Xfrta8',
    appId: '1:1078053511044:ios:e6e42e6824eb06f40ac7d1',
    messagingSenderId: '1078053511044',
    projectId: 'app-sg-db',
    storageBucket: 'app-sg-db.firebasestorage.app',
    iosBundleId: 'com.example.appSg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpzEeUstat8kgxVmaPRJgR5Gi356MTWv8',
    appId: '1:1078053511044:web:41843b3256b43bf90ac7d1',
    messagingSenderId: '1078053511044',
    projectId: 'app-sg-db',
    authDomain: 'app-sg-db.firebaseapp.com',
    storageBucket: 'app-sg-db.firebasestorage.app',
  );
}
